/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a running app and is checked in so the
// baseline has the expected TypeScript shape before dependency installation.
